name: Pull Request

on:
  pull_request:
    branches:
      - 'main'

jobs:
  pr_metrics:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: PR Metrics
        uses: microsoft/PR-Metrics@v1.4.4
        env:
          PR_METRICS_ACCESS_TOKEN: ${{secrets.GITHUB_TOKEN}}
        continue-on-error: true
